bt/urls.py
"""
Gère les redirections du module bt
"""

from django.urls import path

from . import views

app_name = 'bt'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('manage/', views.BlindTestManager.as_view(), name='manage'),
    path('play/', views.BlindTestPlayer.as_view(), name='play'),
    
    path('participate/', views.BlindTestConnectFake.as_view(), name='participate'),
    path('disconnect/', views.BlindTestDisconnectFake.as_view(), name='disconnect'),
]

meltobt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('bt.urls')),
    path('dictator/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

bt/models.py
"""
Gestion des models pour le blind test
"""
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlindTest(models.Model):
    """
    Classe unique qui permet juste de savoir si le blind test est lancé ou pas.
    C'est possible de faire un singleton en django ?
    """
    active = models.BooleanField("actif", default=False)
    
class Theme(models.Model):
    """
    Thème à deviner (ou pas) dans le blind test
    """
    to_guess = models.BooleanField("à deviner ?", default=True)
    indice = models.PositiveSmallIntegerField("n°", default=1)
    hint = models.CharField("nom ou indice", max_length=255, blank=True)
    locked = models.BooleanField("verrouillé", default=False)
    active = models.BooleanField("actif", default=True)
    started_timer = models.DateTimeField("début timer", null=True)
    blindtest = models.ForeignKey(to=BlindTest, on_delete=models.CASCADE, related_name="themes")
    
    def get_relid(self):
        """
        Retourne l'identifiant relatif pour ce thème
        """
        return "t%d" % self.indice
    
class Song(models.Model):
    """
    Morceau à deviner dans le thème du blind test
    """
    indice = models.PositiveSmallIntegerField("n°", default=1)
    hint = models.CharField("nom ou indie", max_length=255, blank=True)
    locked = models.BooleanField("verrouillé", default=False)
    active = models.BooleanField("actif", default=True)
    started_timer = models.DateTimeField("début timer", null=True)
    placeholder = models.CharField("placeholder", max_length=255, blank=True)
    theme = models.ForeignKey(to=Theme, on_delete=models.CASCADE, related_name="songs")
    
    def get_relid(self):
        """
        Retourne l'identifiant relatif pour ce morceau
        """
        return "t%ds%d" % (self.theme.indice, self.indice)
    
    
class UserThemeAnswer(models.Model):
    """
    Gère les réponses des joueurs aux thèmes
    """
    
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    theme = models.ForeignKey(to=Theme, on_delete=models.CASCADE, related_name="themes_answers")
    answer = models.CharField("réponse", max_length=255, blank=True)
    score = models.PositiveSmallIntegerField("points", null=True)
    
    class Meta:
        unique_together = ('user', 'theme')
    
class UserSongAnswer(models.Model):
    """
    Gère les réponses des joueurs aux morceaux
    """
    
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    song = models.ForeignKey(to=Song, on_delete=models.CASCADE, related_name="songs_answers")
    answer = models.CharField("réponse", max_length=255, blank=True)
    score = models.PositiveSmallIntegerField("points", null=True)
    
    class Meta:
        unique_together = ('user', 'song')
    

bt/views.py
"""
Gère les vues pour le blind test
"""
# from random import choice

from django.views import generic
from django.shortcuts import render, redirect

from django.contrib.auth import login, logout

from django.contrib.auth.models import User

# Create your views here.
class IndexView(generic.View):
    """
    Page d'accueil sur laquelle on se connecte
    """
    
    def get(self, request):
        """
        Lorsqu'on arrive sur la page via le get (donc pas en formulaire),
        si on est déjà connecté, on supprime l'utilisateur.
        """
        # if request.user.is_authenticated and not request.user.is_superuser:
        #     # TODO Attention : vrai uniquement pour les comptes "anonymes" mais
        #     # pas pour les comptes twitch ! A voir comment on fait !
        #     # import pdb; pdb.set_trace()
        #     user = User.objects.filter(username=request.user.username)
        #     logout(request)
        #     user.delete()
            
        return render(request, 'bt/index.html')

class BlindTestManager(generic.View):
    """
    Gère le blind test lui-même, côté animateur
    """
    
    def get(self, request):
        """
        Si on est pas un superuser, on est redirigé sur play (petit canaillou)
        """
        if not request.user.is_authenticated or not request.user.is_superuser:
            return redirect('bt:play')
            
        return render(request, 'bt/manage.html')
        
class BlindTestConnectFake(generic.View):
    """
    Gère la création d'un compte avant d'être redirigé sur play
    """
    
    def post(self, request):
        """
        On arrive depuis un formulaire. Si l'username existe déjà, on essaye
        de rajouter un suffixe. Pour la beauté de l'humour.
        """
        
        if request.user.is_authenticated:
            # L'utilisateur est DÉJÀ authentifié, on le renvoie du coup sur le play sans s'emmerder plus que ça.
            return redirect('bt:play')
        
        # suffixes = ['à la butte arc-en-ciel', 'au nounours bien léché',
        #             'à la joie indémontable', "à l'amour inconsidéré",
        #             'au destin fabuleux', 'au recyclage infini',
        #             'à la belle escapade', "à l'oreille absolue",
        #             "à l'originalité folle", 'aux attributs exacerbés',
        #             'aux amitiés multiples', "à l'équidé magique",
        #             'à la célérité incroyable', 'à la précision redoutable',
        #             'à la connaissance exceptionnelle', 'à la fermeté exemplaire',
        #             'aux oreilles pointues', 'à la bouche pulpeuse',
        #             'aux yeux miroitants', "à l'espoir éperdu",
        #             'à la félicité étoilée', 'à la fleur goguenarde',
        #             'au mécréant occis', 'au roseau pliable',
        #             'à la jonquille olfactive', 'au nénufar étendu',
        #             'aux réflexes surhumains', 'à la miséricorde complète',
        #             'au pardon inatteignable', 'au rangement intéressant',
        #             'à la peau veloutée', 'à la chevelure soyeuse',
        #             'au sourire étincelant', "à l'hygiène irréprochable"
        #             'au guet gai', 'au clan déclinant', 'à la taille extraordinaire']
        
        posted_username = request.POST['nickname']
        if posted_username == '':
            posted_username = 'Anonyme'
        
        username = posted_username
        
        inc = 1
        while len(User.objects.filter(username=username)) > 0:
            # username = "%s %s" % (posted_username, choice(suffixes))
            username = "%s %d" % (posted_username, inc)
            inc = inc + 1
        
        user = User.objects.create_user(username=username)
        
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        
        return redirect('bt:play')

class BlindTestDisconnectFake(generic.View):
    """
    Gère la suppression d'un compte avant d'être redirigé sur l'accueil
    """
    
    def get(self, request):
        """
        Si un compte est connecté, on le déconnecte et on le supprime. Aussi simple que ça.
        """
        if request.user.is_authenticated and not request.user.is_superuser:
            # TODO Attention : vrai uniquement pour les comptes "anonymes" mais
            # pas pour les comptes twitch ! A voir comment on fait !
            # import pdb; pdb.set_trace()
            user = User.objects.filter(username=request.user.username)
            logout(request)
            user.delete()
        
        return redirect('bt:index')

class BlindTestPlayer(generic.View):
    """
    Affichage du formulaire de jeu côté joueur
    """
    
    def get(self, request):
        """
        Si on est pas connecté, on est redirigé sur l'index, sinon on peut jouer :D
        """
        if not request.user.is_authenticated:
            return redirect('bt:index')
        return render(request, 'bt/play.html')

bt/templates/bt/base.html
{% load static %}

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Blind-test Melto - Participation</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/darkly/bootstrap.min.css" rel="stylesheet" integrity="sha384-rCA2D+D9QXuP2TomtQwd+uP50EHjpafN+wruul0sXZzX/Da7Txn4tB9aLMZV4DZm" crossorigin="anonymous">
    <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'bt/css/bt.css' %}" />
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'bt/css/all.css' %}" rel="stylesheet">
    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    
</head>
<body>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

bt/templates/bt/index.html
{% extends 'bt/base.html' %}
{% load static %}
{% load socialaccount %}

{% block content %}
<h3>Bienvenue au Blind-test du Burnout !</h3>

<div class="text-justify d-none">
    <p>Le fonctionnement est simple : vous écoutez les musiques sur le live du <a href="https://www.twitch.tv/MeltdownMtpl" target="_blank">Meltdown Montpellier (suivez-nous !)</a>, et vous avez la possibilité de saisir le titre et l'artiste et éventuellement les autres informations demandées. Une fois que vous validez votre réponse, vous pouvez la modifier tant qu'elle n'a pas été corrigée par notre animateur en chef. Une fois noté, vous ne pouvez plus faire marche arrière, réfléchissez donc bien avant de valider votre réponse !</p>
    <p>L'animateur peut changer sa note donc pour toute contestation, c'est à vos risques et périls et c'est sur le chat du stream directement que ça se passe.</p>
    <p>S'il y a un thème à trouver, vous pouvez aussi le saisir dans la case correspondante.</p>
    <p>En cas de souci, contactez @renkineko sur Twitter ou parlez-en à l'animateur qui me fera probablement suivre l'info ! :)</p>
</div>

<div class="text-center">
    <p>Un téléphone par équipe</p>
</div>

<div class="row justify-content-center">
    {% if user.is_authenticated and user.is_superuser %}
            <div class="col-6 text-center">
                <a href="{% url 'bt:manage' %}" class="btn btn-primary w-100"><i class="fas fa-music"></i> Gestion du blind test <i class="fas fa-music"></i></a>
            </div>
    {% else %}
        {% if user.is_authenticated %}
            <div class="col-6 text-center">
                <a href="{% url 'bt:play' %}" class="btn btn-primary w-100"><i class="fas fa-music"></i> Revenir au blind test <i class="fas fa-music"></i></a>
            </div>
            <div class="col-6 text-center">
                <a href="{% url 'bt:disconnect' %}" class="btn btn-danger w-100"><i class="fas fa-times-circle"></i> Annuler ma participation <i class="fas fa-times-circle"></i></a>
                <small class="text-muted">Attention : ça détruira votre score, vous n'aurez plus rien pour le blind test en cours.</small>
            </div>
        {% else %}
        <div class="col-6 text-center">
            <p>Pour commencer, choisissez votre nom d'équipe.</p>
                <form method="post" action="{% url 'bt:participate' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="nickname">Nom d'équipe</label>
                        <input type="text" autocomplete="off" maxlength="32" class="form-control" id="nickname" name="nickname" aria-describedby="nicknameHelp" placeholder="Roxxxor du 34">
                        <small id="nicknameHelp" class="form-text text-muted">Si votre nom d'équipe est déjà pris pour cette partie, vous aurez un chiffre rajouté. Soyez original.</small>
                    </div>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-headphones"></i> Participer au blind-test <i class="fas fa-headphones"></i></button>
                </form>
            </div>
        {% endif %}
    {% endif %}
</div>


{% endblock content %}

bt/templates/bt/manage.html
{% extends 'bt/base.html' %}
{% load static %}

{% block content %}
<h3>Bienvenue animateur</h3>


<div class="row">
    <div class="col-6 mb-3">
        <button type="button" id="btnStart" class="btn btn-success w-100"><i class="fas fa-play-circle"></i> Lancer le blind test (réinitialise tout) <i class="fas fa-play-circle"></i></button>
    </div>
    <div class="col-6 mb-3">
        <button type="button" id="btnStop" class="btn btn-danger w-100" disabled><i class="fas fa-stop-circle"></i> Arrêter le BT <i class="fas fa-stop-circle"></i> </button>
    </div>
    <div class="col-6 mb-3">
        <div class="btn-group w-100" role="group" aria-label="Nouvelle manche à thème">
            <button type="button" id="btnTheme" class="btn btn-primary" disabled><i class="fas fa-question-circle"></i> Nouvelle manche (avec thème) <i class="fas fa-question-circle"></i></button>
            <button type="button" id="btnTimerTheme" class="btn btn-primary text-danger stop-watch" disabled><i class="fas fa-stopwatch"></i><span id="remainingTimeTheme"></span></button>
        </div>
    </div>
    <div class="col-6 mb-3">
        <button type="button" id="btnNoTheme" class="btn btn-warning w-100" disabled><i class="fas fa-times-circle"></i> Nouvelle manche (sans thème) <i class="fas fa-times-circle"></i></button>
    </div>
    <div class="col-12 mb-3">
        <div class="btn-group w-100" role="group" aria-label="Nouvelle manche à thème">
            <button type="button" id="btnSong" class="btn btn-secondary" disabled><i class="fas fa-plus-circle"></i> Nouvelle musique <i class="fas fa-plus-circle"></i></button>
            <button type="button" id="btnTimerSong" class="btn btn-secondary text-danger stop-watch" disabled><i class="fas fa-stopwatch"></i><span id="remainingTimeSong"></span></button>
        </div>
    </div>
    <div class="col-3" id="mvp1">
        <h6>MVP (<span>NC</span> points)</h6>
        <span></span>
    </div>
    <div class="col-3" id="mvp2">
        <h6>2<sup>nd</sup> (<span>NC</span> points)</h6>
        <span></span>
    </div>
    <div class="col-3" id="mvp3">
        <h6>3<sup>eme</sup> (<span>NC</span> points)</h6>
        <span></span>
    </div>
    <div class="col-3" id="mvp4">
        <h6>Av. dernier (<span>NC</span> points)</h6>
        <span></span>
    </div>
    <div class="col-12">
        <button type="button" id="btnScores" class="btn btn-info w-100"><i class="fas fa-crown"></i> Récap total des scores <i class="fas fa-crown"></i></button>
    </div>
</div>

<template id="tplTheme">
    <div class="card col-12 my-2 current-theme">
        <div class="card-header">
            <a class="text-decoration-none" data-toggle="collapse" href="#collapsenum" aria-expanded="true" aria-controls="collapsenum">
                <h6 class="font-weight-bold font-italic mb-0 text-center">
                    <span>Thème nom</span>
                </h6>
            </a>
        </div>
        <div id="collapsenum" class="collapse show" aria-labelledby="collapsenum">
            <div class="card-body">
                <table class="table table-bordered w-100">
                    <thead>
                        <tr>
                            <th style="width: 50px;">Type</th>
                            <th style="width: 200px;">Attendu...</th>
                            <th>Réponses</th>
                        </tr>
                    </thead>
                    <tbody class="tbody-theme">
                        <tr class="theme bg-info">
                            <td><i class="fas fa-book" alt="theme"></i></td>
                            <td class="expected"></td>
                            <td class="answers">
                                <div class="pl-2 pr-2 row"></div>
                            </td>
                        </tr>
                    </tbody>
                    <tbody class="tbody-song"></tbody>
                </table>
            </div>
        </div>
    </div>
</template>
<template id="tplNoTheme">
    <div class="card col-12 my-2 current-theme">
        <div class="card-header">
            <a class="text-decoration-none" data-toggle="collapse" href="#collapsenum" aria-expanded="true" aria-controls="collapsenum">
                <h6 class="font-weight-bold font-italic mb-0 text-center">
                    <span>Thème nom</span>
                </h6>
            </a>
        </div>
        <div id="collapsenum" class="collapse show" aria-labelledby="deplacementnum">
            <div class="card-body">
                <table class="table table-bordered w-100">
                    <thead>
                        <tr>
                            <th style="width: 50px;">Type</th>
                            <th style="width: 200px;">Attendu...</th>
                            <th>Réponses</th>
                        </tr>
                    </thead>
                    <tbody class="tbody-song"></tbody>
                </table>
            </div>
        </div>
    </div>
</template>
<template id="tplSong">
    <tr class="current-song">
        <td><i class="fas fa-music"></i></td>
        <td class="expected">Nom chanson</td>
        <td class="answers">
            <div class="pl-2 pr-2 row"></div>
        </td>
    </tr>
</template>
<template id="tplAnswer">
    <div class="col-12 col-md-6 col-xl-3 mb-2 border div-answer">
        <div class="mb-1"><i class="fas fa-user"></i> <span class="nickname">Pseudo</span></div>
        <div class="mb-1"><i class="align-top fas fa-pen"></i> <div class="d-inline-block user-answer">Answer</div></div>
        <div class="btn-group btn-group-sm" role="group" aria-label="note">
            <button type="button" val="0" class="not-initialized btn btn-secondary">0</button>
            <button type="button" val="1" class="not-initialized btn btn-secondary">1</button>
            <button type="button" val="2" class="not-initialized btn btn-secondary">2</button>
            <button type="button" val="3" class="not-initialized btn btn-secondary">3</button>
            <button type="button" val="4" class="not-initialized btn btn-secondary">4</button>
            <button type="button" val="5" class="not-initialized btn btn-secondary">5</button>
        </div>
    </div>
</template>
<div class="modal fade" id="finalResults" tabindex="-1" role="dialog" aria-labelledby="finalResultsLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="finalResultsLabel">Résumé des scores</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <template id="tplResult">
                    <div class="col-3 my-1 border"><span class="finalResultUsername"></span> - <span class="finalResultPoints"></span></div>
                </template>
                <div class="row" id="finalResultsDiv">
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="expectedThemeAnswer" tabindex="-1" role="dialog" aria-labelledby="expectedThemeAnswerLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="expectedThemeAnswerLabel">Nouveau thème</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="expectedThemeAnswerForm">
                    <div class="form-group">
                        <label for="expectedTheme" class="col-form-label">Thème à deviner ?</label>
                        <input type="text" autocomplete="off" maxlength="255" class="form-control" aria-describedby="expectedThemeHelp" id="expectedTheme">
                        <small id="expectedThemeHelp" class="form-text text-muted">C'est juste pour info, la validation reste manuelle. Ce sera le titre de la section.</small>
                    </div>
                    <div class="d-none">
                        <input type="submit" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAddTheme">Ajouter</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="expectedSongAnswer" tabindex="-1" role="dialog" aria-labelledby="expectedSongAnswerLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="expectedSongAnswerLabel">Nouvelle musique</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="expectedSongAnswerForm">
                    <div class="form-group">
                        <label for="expectedSong" class="col-form-label">Musique à deviner ?</label>
                        <input type="text" autocomplete="off" maxlength="255" class="form-control" aria-describedby="expectedSongHelp" id="expectedSong">
                        <small id="expectedSongHelp" class="form-text text-muted">C'est juste pour info, la validation reste manuelle. Le titre sera présent sur la ligne, pour aider à la correction.</small>
                    </div>
                    <div class="form-group">
                        <label for="placeholderSong" class="col-form-label">Placeholder</label>
                        <input type="text" autocomplete="off" maxlength="255" class="form-control" id="placeholderSong">
                        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                            <button type="button" placeholder-value="Artiste + titre" class="btn btn-secondary">Classique</button>
                            <button type="button" placeholder-value="Tous les artistes + titre" class="btn btn-secondary">Précis</button>
                            <button type="button" placeholder-value="Artiste original (pas du remix) + titre" class="btn btn-secondary">Remix</button>
                            <button type="button" placeholder-value="Œuvre associée (film, série, anime, jeu vidéo...)" class="btn btn-secondary">Fourre-tout</button>
                            <button type="button" placeholder-value="Titre précis de l'œuvre associée (n° d'opus ou sous-titre...)" class="btn btn-secondary">Fourre-tout précis</button>
                            <button type="button" placeholder-value="" class="btn btn-secondary">Vide</button>
                        </div>
                    </div>
                    <div class="d-none">
                        <input type="submit" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAddSong">Ajouter</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>
<div id="answers" class="row">
    
</div>

<script src="{% static 'bt/js/manager.js' %}"></script>
{% endblock content %}